services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka-config.properties:/etc/kafka/server.properties
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    ports:
      - "8080:8080"
    networks:
      - kafka-network

  subway-producer:
    build:
      context: ./subway-producer
    environment:
      KAFKA_URL: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  weather-producer:
    build:
      context: ./weather-producer
    environment:
      KAFKA_URL: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  websocket-server:
    build:
      context: ./websocket-server
    environment:
      KAFKA_URL: kafka:9092
      WS_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - subway-producer
      - weather-producer
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
    driver: local
